### PR TITLE
Add a new option for hiding the underline

### LINKED ISSUE #22: Option to hide underline for preedit by default for all Vietnamese input methods
Vietnamese has a little different from Chinese or Japanese, on Windows with Unikey or Android with Laban Key, we don't have underline. So when people come to Linux, most of people don't like underline when we're typing. If can, please hide it by default. Thank you.

### PR DESCRIPTION
**Pull request by trmdi**
Show the underline by default.

Close #22

### CODE REVIEW

**Comment by trmdi** [comment]
@wengxt 
Why does this option work oppositely in Telegram?

**Comment by wengxt** [comment]
seems to be a bug in fcitx-qt5. I guess you’re using flatpak telegram instead of native or sth?

**Comment by trmdi** [comment]
> seems to be a bug in fcitx-qt5. I guess you’re using flatpak telegram instead of native or sth?

I'm using the native version from OpenSUSE Tumbleweed's official repo.

**Comment by wengxt** [comment]
it really depends on how your tg is complied whether it’s using system qt. it’s still possible it’s statically linked a fcitx4 plugin.

**Comment by wengxt** [comment]
Or for some reason you're using the fcitx4 plugin. Actually I'm reading the spec file: DESKTOP_APP_USE_PACKAGED=On so it should use system version?

Can you try `QT_DEBUG_PLUGINS=1 telegram-desktop`

Also, can you post the output of following command when telegram-desktop is running?
```
dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
```

**Comment by trmdi** [comment]
[dbus.log](https://github.com/fcitx/fcitx5-unikey/files/10037099/dbus.log)
[telegram.log](https://github.com/fcitx/fcitx5-unikey/files/10037100/telegram.log)

**Comment by trmdi** [comment]
> Or for some reason you're using the fcitx4 plugin

You're right:
>qt.core.plugin.factoryloader: Got keys from plugin meta data QList("fcitx", "fcitx5")
> qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforminputcontexts" ...
> qt.core.library: "/usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin-qt6.so" loaded library

No idea why it prefers to load fcitx4 plugin?

**Comment by wengxt** [comment]
> > Or for some reason you're using the fcitx4 plugin
> 
> You're right:
> 
> > qt.core.plugin.factoryloader: Got keys from plugin meta data QList("fcitx", "fcitx5")
> > qt.core.plugin.factoryloader: checking directory path "/usr/bin/platforminputcontexts" ...
> > qt.core.library: "/usr/lib64/qt6/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin-qt6.so" loaded library
> 
> No idea why it prefers to load fcitx4 plugin? Maybe a distro's bug, fcitx5 and fcitx4 plugin should never co-exist?

Qt doesn't really pick since there's no priority. fcitx-qt6 might be pulled in if you have fcitx installed on your system? Anyway no need to have both fcitx and fcitx5 plugin installed.

As for the PR itself, please remember to run clang-format next time.

**Comment by trmdi** [comment]
What about MS Edge and Konsole? this need to be fixed in their sides?

**Comment by wengxt** [comment]
I have no idea what ms edge do. they might not respect gtk's hint anyway.

for konsole, it's understandable that terminal can't do all kinds of input method preedit styling. It just doesn't fit.

**Comment by wengxt** [comment]
@trmdi I don't know how I could contact you (didn't see you on the telegram or irc), but are you interested in contributing the localization? (asking this because you're adding a new string in this PR).

You may do the i18n work on transifex (need to register and request join the team): https://www.transifex.com/fcitx/teams/12005/vi/

The translation are sync'ed to github by a cron job.

**Comment by trmdi** [comment]
Ok I will do that. :)

**Comment by trmdi** [comment]
@wengxt
How could I request to join the team?
My Transifex profile: https://www.transifex.com/user/profile/trmdi/
Email: trmdi@yandex.com

**Comment by wengxt** [comment]
https://www.transifex.com/fcitx/teams/ try this page maybe?

**Comment by trmdi** [comment]
image

**Comment by wengxt** [comment]
did you verify your email address or sth? Maybe check your spam box. because I can’t even find your user id when I search.

**Comment by trmdi** [comment]
Maybe a bug of transifex when you login with the Github account.
Solved and I've sent a request.

**Comment by wengxt** [comment]
@trmdi approved

**Pull request merged**
