### PR TITLE
Allow "uoh" when going with "h", "kh" or standing alone

### LINKED ISSUE #24: Can't type word huơ
I can't type word "huơ"  (huơ  tay)

huow become hươ instead huơ

### PR DESCRIPTION
**Pull request by trmdi**
Now you can type "uơ", "huơ", "khuơ".
Fix #24

### CODE REVIEW

**Comment by trmdi** [comment]
Can you test this? @zenfas

**Comment by zenfas** [comment]
Sorry, I can't test atm. I confused 2 things:
1) Stand alone maybe effect word "ươ" 
2) Maybe issue same other Input Method (VNI, VIQR, other Telex...), not yet test.

**Comment by trmdi** [comment]
> Stand alone maybe effect word "ươ"

You can type "uwow".

**Comment by Nekosha** [comment]
Telex `huowu`, VNI `huo7u` -> `huơu` is an invalid sequence.
As `huown` gives `hươn`, should we apply the same processing to `huowu`?
Note: `huouw` (or `huou7`) does give the expected `hươu`

**Comment by zenfas** [comment]
How about "khương" @Nekosha

**Comment by zenfas** [comment]
uơ  don't anything letter at the end, if have another letter follow, it should become ươ, ex: ươi, ươu, ướt..

**Comment by Nekosha** [comment]
@zenfas The issue only affects vowels as consonants have a check for this.
`UkEngine::appendConsonnant`
```cpp
    //...
    case vnw_cv:
        //...
        if (vs == vs_uoh || vs == vs_uho) {
            newVs = vs_uhoh;
        }
        //...
        if (isValid) {
            // check u+o -> u+o+ <--- this comment should be
            //                        check u+o, uo+ -> u+o+
            if (vs == vs_uho) {
                markChange(m_current - 1);
                prev.vnSym = vnl_oh;
                prev.vseq = vs_uhoh;
                complexEvent = true;
            } else if (vs == vs_uoh) {
                markChange(m_current - 2);
                m_buffer[m_current - 2].vnSym = vnl_uh;
                m_buffer[m_current - 2].vseq = vs_uh;
                prev.vseq = vs_uhoh;
                complexEvent = true;
            }
```
A similar check can be implemented in `UkEngine::appendVowel`.
Actually, `VSeqList[]` seems to have entries for this, but I wasn't able to get it to work.

**Comment by zenfas** [comment]
@tulequ sorry for disturb, can you give some advice to fix error in libunikey for both ibus- unikey and fcitx5-unikey, thank you

**Review by Nekosha — CHANGES_REQUESTED** [review]
Line 1974
```cpp
                m_buffer[m_current - 2].vnSym = vnl_uh;
                m_buffer[m_current - 2].vseq = vs_uh;            
+               prev.vseq = vs_uhoh;    // <--- Why is this left out?
```

Line 1977 
```cpp
            vs = vs_uhoh;    // should be newVs = vs_uhoh;
            complexEvent = true;
```

**Comment by Nekosha** [comment]
Tone mark position is not recalculated on conversion
`Buwroi` (`Bu73oi`) -> `bửơi` (Expected `bưởi`)
The u+o+ conversion should be moved after getting previous tone position.
`complexEvent` is also unnecessary.
```diff
+       prevTonePos = (m_current - 1) - (VSeqList[vs].len - 1) +
+                     getTonePosition(vs, true);
+       tone = m_buffer[prevTonePos].tone;

        // u+o/uo+ + u/i -> u+o+ + u/i
        if ((vs == vs_uoh || vs == vs_uho) &&
             (lowerSym == vnl_i || lowerSym == vnl_u)) {

         // ...

            vs = vs_uhoh;
-           complexEvent = true;
        }

-       prevTonePos = (m_current - 1) - (VSeqList[vs].len - 1) +
-                     getTonePosition(vs, true);
-       tone = m_buffer[prevTonePos].tone;

// ...

-      if (complexEvent) {
-         return 1;
-      }
```

**Comment by trmdi** [comment]
>  complexEvent is also unnecessary.

Can you type "huwou" without this? @Nekosha

**Comment by Nekosha** [comment]
> Can you type "huwou" without this? @Nekosha

Broken, my bad. Should keep it.

**Comment by Nekosha** [comment]
Seems ready to merge.
Final fix, GCC complains with -Wall
```
/home/buildbot/sources/fcitx5-unikey/unikey/ukengine.cpp: In member function 'int UkEngine::processHookWithUO(UkKeyEvent&)':
/home/buildbot/sources/fcitx5-unikey/unikey/ukengine.cpp:1272:57: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
 1272 |                     (m_buffer[m_current].form == vnw_cv &&
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
 1273 |                         (m_buffer[m_current - 2].cseq == cs_h  ||
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1274 |                          m_buffer[m_current - 2].cseq == cs_kh ||
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1275 |                          m_buffer[m_current - 2].cseq == cs_th   ) ||
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ```

**Comment by trmdi** [comment]
Thank you. Now is your turn @wengxt

**Comment by trmdi** [comment]
A question. Should "hư+o" be auto completed to "hươ" right away? Currently you need an extra "u/i" to get that done (similar to Laban Key)

**Comment by trmdi** [comment]
Ping!

**Comment by zenfas** [comment]
> Ping!

I think @wengxt think about "th***" (thuở, thương...)
Can we edit the same case with "th**", no need add new sesstion

**Comment by trmdi** [comment]
> > Ping!
> 
> I think @wengxt think about "th***" (thuở, thương...) Can we edit the same case with "th**", no need add new sesstion

What do you mean? You can't type those words?

**Comment by tulequ** [comment]
> @tulequ sorry for disturb, can you give some advice to fix error in libunikey for both ibus- unikey and fcitx5-unikey, thank you

sorry for late reply
I'm very happy to share the owner of the [vn-input](https://github.com/vn-input) org. So more dev can work on it

All *unikey related projects can move to there if required

**Comment by zenfas** [comment]
> > > Ping!
> > 
> > 
> > I think @wengxt think about "th***" (thuở, thương...) Can we edit the same case with "th**", no need add new sesstion
> 
> What do you mean? You can't type those words?

@trmdi: Mr @wengxt  worry about diff between fcitx5-unikey and upstream if apply this PR. Noone update upstream
P/S: @trmdi bạn có thể tham gia maintain https://github.com/vn-input để đảm bảo unikey được cật nhật trên linux không?
Về PR này, mình có thắc mắc, nếu các từ bắt đầu "th***" thì có thể gõ bình thường, vậy mình có thể bổ sung trường hợp bắt đầu với "h***" hoặc "kh***" vào chung trường hợp ấy được không?

**Comment by trmdi** [comment]
> > > > Ping!
> > > 
> > > 
> > > I think @wengxt think about "th***" (thuở, thương...) Can we edit the same case with "th**", no need add new sesstion
> > 
> > 
> > What do you mean? You can't type those words?
> 
> @trmdi: Mr @wengxt worry about diff between fcitx5-unikey and upstream if apply this PR. Noone update upstream P/S: @trmdi bạn có thể tham gia maintain https://github.com/vn-input để đảm bảo unikey được cật nhật trên linux không? Về PR này, mình có thắc mắc, nếu các từ bắt đầu "th***" thì có thể gõ bình thường, vậy mình có thể bổ sung trường hợp bắt đầu với "h***" hoặc "kh***" vào chung trường hợp ấy được không?

Where did @wengxt say that?

**Comment by zenfas** [comment]
Telegram group

**Comment by tulequ** [comment]
@trmdi or just create a PR to vn-input projects after finished here

**Comment by trmdi** [comment]
> @trmdi or just create a PR to vn-input projects after finished here

Ok, what do you think @wengxt ?

**Comment by wengxt** [comment]
Please rebase against master and try to fix all the test case failure and update the test where the test need to be updated.

With the new test cases I noticed lots of changes. And in my testing with other vi input method, the result they produced are mixed, so I can't really say if the change are expected or unexpected.

**Comment by trmdi** [comment]
> And in my testing with other vi input method, the result they produced are mixed, so I can't really say if the change are expected or unexpected.

What did you find? In case I forgot about that.

**Comment by wengxt** [comment]
> > And in my testing with other vi input method, the result they produced are mixed, so I can't really say if the change are expected or unexpected.
> 
> What did you find? In case I forgot about that.

Disclaimer: I disable spell check in the tests below and I don't know whether they are valid Vietnamese word. I'd really need native speaker help to decide which one is correct, or if it doesn't matter, which one "makes more sense"

for uow case:
laban and ios built-in telex -> ươ 
with your PR -> uơ .

for thuowi result:
unikey, laban -> thuơi 
bamboo, ios -> thươi 

uowf:
bamboo -> uờ 
ios/laban -> ườ

**Comment by trmdi** [comment]
> for uow case:
> laban and ios built-in telex -> ươ
> with your PR -> uơ .

"uơ" is never used as a standalone word. But the ability to type it makes sense, for example when you are a Vietnamese teacher, you need to type it sometimes.

> for thuowi result:
> unikey, laban -> thuơi
> bamboo, ios -> thươi

"uơi" never exists in any case, there is only "ươi"

> uowf:
> bamboo -> uờ
> ios/laban -> ườ

This one never stands alone too. But the ability to type it can be useful in some cases like I talked above.

**Comment by zenfas** [comment]
"uơi" in "quới"

**Comment by trmdi** [comment]
> "uơi" in "quới"

What do you mean? It's still possible to type that word.

**Comment by zenfas** [comment]
Just remind that word

**Comment by trmdi** [comment]
> Just remind that word

"u" in that case is considered go with "qu" as a consonent, not with "uoi".

**Pull request merged**
