### PR TITLE
Fix #28

### LINKED ISSUE #28: Type "s" after "reset" return "resetét" if Enable Macro is enabled
**Steps to reproduce:**
\- Type "reset" into a text box
\- Focus out of the text box
\- Go back and type "s" after "reset"

**Expected result:** "resets"

**Actual result:** "resetét"

**Note:** This does not happen when you disable "Enable Macro"

### PR DESCRIPTION
**Pull request by trmdi**
Use surrounding string only when its previous char is valid

### CODE REVIEW

**Comment by trmdi** [comment]
@Nekosha Could you help to test it?

**Comment by wengxt** [comment]
the fix is not correct. 

The bug has two points:
1. the started point contains 1 more character
2. it doesn't check correct if the previous state is a whole word.

**Comment by trmdi** [comment]
Is the rebuild surrounding function supposed to search for previously surrounding sequences e.g. q, kh, th... right?

**Comment by wengxt** [comment]
see my fix above

**Pull request closed without merging**
